import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import { Toaster } from "@/components/ui/toaster";
import LayoutClientWrapper from "@/components/LayoutClientWrapper";

export const metadata = {
  title: "Gadgex",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <LayoutClientWrapper>
            {children}
          </LayoutClientWrapper>
        </ReduxProvider>
        <Toaster />
      </body>
    </html>
  );
}
