import "./globals.css";
import { getServerSession } from "next-auth";
import ReduxProvider from "@/redux/ReduxProvider";
import { Toaster } from "@/components/ui/toaster";
import { authOptions } from "./api/auth/[...nextauth]/route";
import LayoutClientWrapper from "@/components/LayoutClientWrapper";

export const metadata = {
  title: "Gadgex",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <LayoutClientWrapper session={session}>
            {children}
          </LayoutClientWrapper>
        </ReduxProvider>
        <Toaster />
      </body>
    </html>
  );
}
